In [7]:
import numpy as np


def matrixKey (key):
    myMatrix=np.zeros((5,5),dtype=str)
    count=0
    for i in range(5):
        for j in range(5):
         if  count < len(key):
           if key[count] not in myMatrix : 
             myMatrix[i][j]=key[count]
             count+=1
         else:
                for b in range(122, 96, -1):
                 if chr(b) not in myMatrix and chr(b) !="j":
                     myMatrix[i,j]=chr(b)
    print(myMatrix)
    return myMatrix



def encryption(plainT, myMatrix):
    pairlist=[]
    cipher=""
    if len(plainT)%2 !=0:
        plainT+="x"
    
    plainT=plainT.replace("j","i")
    for i in range (0,len(plainT),2):
        if i<len(plainT)-1:
            if plainT[i]==plainT[i+1]:
                plainT=plainT[:i+1]+"x"+plainT[i+1:]
        pairlist.append(plainT[i]+plainT[i+1])
        row=np.argwhere(myMatrix == plainT[i] )
        col=np.argwhere(myMatrix == plainT[i+1] )
        print(row,col)
        if row[0][0]== col[0][0]:
            rr=row[0][1]+1
            if row[0][1]==4:
               rr=0 
            letter=myMatrix[col[0][0]][rr]
        elif row[0][1]== col[0][1]:
            rr=row[0][0]+1
            if row[0][0]==4:
               rr=0 
            letter=myMatrix[rr][col[0][1]]
        else:
            letter=myMatrix[row[0][0]][col[0][1]]
        cipher+=letter
        col=np.argwhere(myMatrix == plainT[i] )
        row=np.argwhere(myMatrix == plainT[i+1] )
        if row[0][0]== col[0][0]:
            rr=row[0][1]+1
            if row[0][1]==4:
               rr=0 
            letter=myMatrix[col[0][0]][rr]
        elif row[0][1]== col[0][1]:
            rr=row[0][0]+1
            if row[0][0]==4:
               rr=0 
            letter=myMatrix[rr][col[0][1]]
        else:
            letter=myMatrix[row[0][0]][col[0][1]]
        cipher+=letter
        
    print(cipher)
    return cipher

def dycryption(ct, myMatrix):
    pairlist=[]
    cipher=""
    if len(ct)%2 !=0:
        ct+="x"
    for i in range (0,len(ct),2):
        pairlist.append(ct[i]+ct[i+1])
        row=np.argwhere(myMatrix == ct[i] )
        col=np.argwhere(myMatrix == ct[i+1] )
        print(row,col)
        if row[0][0]== col[0][0]:
            rr=row[0][1]-1
            if row[0][1]==0:
               rr=4 
            letter=myMatrix[col[0][0]][rr]
        elif row[0][1]== col[0][1]:
            rr=row[0][0]-1
            if row[0][0]==0:
               rr=4 
            letter=myMatrix[rr][col[0][1]]
        else:
            letter=myMatrix[row[0][0]][col[0][1]]
        cipher+=letter
        col=np.argwhere(myMatrix == ct[i] )
        row=np.argwhere(myMatrix == ct[i+1] )
        if row[0][0]== col[0][0]:
            rr=row[0][1]-1
            if row[0][1]==0:
               rr=4
            letter=myMatrix[col[0][0]][rr]
        elif row[0][1]== col[0][1]:
            rr=row[0][0]-1
            if row[0][0]==0:
               rr=4 
            letter=myMatrix[rr][col[0][1]]
        else:
            letter=myMatrix[row[0][0]][col[0][1]]
        cipher+=letter
    print(cipher)
m=matrixKey("key") 

pt=encryption("arwaa", m)  
dycryption(pt,m)



       
        
        
    
                     

            



[['k' 'e' 'y' 'a' 'b']
 ['c' 'd' 'f' 'g' 'h']
 ['i' 'l' 'm' 'n' 'o']
 ['p' 'q' 'r' 's' 't']
 ['u' 'v' 'w' 'x' 'z']]
[[0 3]] [[3 2]]
[[4 2]] [[0 3]]
[[0 3]] [[4 3]]
ysxyga
[[0 2]] [[3 3]]
[[4 3]] [[0 2]]
[[1 3]] [[0 3]]
arwaax
